[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "tfreezer"
version = "1.0.0"
description = "Freeze application made with python."
readme = "README.md"
requires-python = ">=3.11"
# license = {file = "LICENSE"}
authors = [
    {name = "Tac", email = "cookiezhx@163.com"},
]
dependencies = [
    "mypy[mypyc]",
    "pyinstaller>=6.11.0",
]

[project.optional-dependencies]
dev = [
    "pylint",
    "black",
    "debugpy",
    "requests",
    "pywin32",
    "pyqt5",
]

[project.urls]
Homepage = "https://github.com/Tac213/tfreezer"
Repository = "https://github.com/Tac213/tfreezer"

[tool.black]
line-length = 140
target-version = ['py311']
include = '\.pyi?$'
# 'extend-exclude' excludes files or directories in addition to the defaults
extend-exclude = '''
# A regex preceded with ^/ will apply only to files and directories
# in the root of the project.
(
  ^/foo.py    # exclude a file named foo.py in the root of the project
  | .*_pb2.py  # exclude autogenerated Protocol Buffer files anywhere in the project
  | .*resource_view_rc.py  # exclude autogenerated qt rc file
)
'''

[tool.setuptools.package-data]
"tfreezer.cppsrc" = ["**/*.cpp", "**/*.cmake", "**/CMakeLists.txt"]
