# -*- coding: utf-8 -*-
# author: Tac
# contact: cookiezhx@163.com

"""
Script for building packages that can be loaded by tfloader.
"""

from typing import Optional
import sys
import os
import re
import argparse
import shutil
import multiprocessing

from PyInstaller.building import build_main

from tfreezer import log, utils, generate_frozen_modules, paths, assemble_application


FROZEN_MODULES_HEADER_SRC = """\
// Generated by: tfreezer.package_builder
#include "Python.h"
{frozen_headers}

static struct _frozen TFPackage_FrozenModules[] = {{
{module_infos}
    {{0, 0, 0}}  /* sentinel */
}};
"""

MAIN_C_SRC = """\
// Generated by: tfreezer.package_builder
#include "Python.h"
#include "frozen_modules/frozen_modules.h"

#if defined(_WIN32) || defined(__CYGWIN__)
    #define TFPACKAGE_EXPORTED __declspec(dllexport)
#else
    #define TFPACKAGE_EXPORTED
#endif

#define TFPACKAGE_INIT_FUNC TFPACKAGE_EXPORTED struct _frozen*

TFPACKAGE_INIT_FUNC
TFPackage_{pkgname}(void)
{{
    return TFPackage_FrozenModules;
}}
"""

CMAKE_SRC = """\
# Generated by: tfreezer.package_builder
cmake_minimum_required(VERSION 3.4...3.18)
project({pkgname})

if(NOT DEFINED PYTHON_EXECUTABLE)
    message(FATAL_ERROR "PYTHON_EXECUTABLE is not set.")
endif()

if(NOT TARGET cpython::libpython)
    add_subdirectory(cpython)
endif()

add_library({pkgname} SHARED main.c)

target_link_libraries(
    {pkgname}
    PRIVATE
        cpython::libpython
)

add_custom_command(TARGET {pkgname} POST_BUILD
    COMMAND ${{CMAKE_COMMAND}} -E copy $<TARGET_FILE:{pkgname}> ${{CMAKE_LIBRARY_OUTPUT_DIRECTORY}}
    COMMAND_EXPAND_LISTS
)
"""

# We need to exclude binaries that already exist in a normal tfreezer-frozen application.
# Reference: https://github.com/pyinstaller/pyinstaller/blob/develop/PyInstaller/depend/dylib.py
_BINARY_EXCLUDES = {
    # Visual Studio 2010 (VC10) runtime
    # http://msdn.microsoft.com/en-us/library/8kche8ah(v=vs.100).aspx
    r"atl100\.dll",
    r"msvcr100\.dll",
    r"msvcp100\.dll",
    r"mfc100\.dll",
    r"mfc100u\.dll",
    r"mfcmifc80\.dll",
    r"mfcm100\.dll",
    r"mfcm100u\.dll",
    # Visual Studio 2012 (VC11) runtime
    # https://docs.microsoft.com/en-us/visualstudio/releases/2013/2012-redistribution-vs
    #
    # VC110.ATL
    r"atl110\.dll",
    # VC110.CRT
    r"msvcp110\.dll",
    r"msvcr110\.dll",
    r"vccorlib110\.dll",
    # VC110.CXXAMP
    r"vcamp110\.dll",
    # VC110.MFC
    r"mfc110\.dll",
    r"mfc110u\.dll",
    r"mfcm110\.dll",
    r"mfcm110u\.dll",
    # VC110.MFCLOC
    r"mfc110chs\.dll",
    r"mfc110cht\.dll",
    r"mfc110enu\.dll",
    r"mfc110esn\.dll",
    r"mfc110deu\.dll",
    r"mfc110fra\.dll",
    r"mfc110ita\.dll",
    r"mfc110jpn\.dll",
    r"mfc110kor\.dll",
    r"mfc110rus\.dll",
    # VC110.OpenMP
    r"vcomp110\.dll",
    # DIA SDK
    r"msdia110\.dll",
    # Visual Studio 2013 (VC12) runtime
    # https://docs.microsoft.com/en-us/visualstudio/releases/2013/2013-redistribution-vs
    #
    # VC120.CRT
    r"msvcp120\.dll",
    r"msvcr120\.dll",
    r"vccorlib120\.dll",
    # VC120.CXXAMP
    r"vcamp120\.dll",
    # VC120.MFC
    r"mfc120\.dll",
    r"mfc120u\.dll",
    r"mfcm120\.dll",
    r"mfcm120u\.dll",
    # VC120.MFCLOC
    r"mfc120chs\.dll",
    r"mfc120cht\.dll",
    r"mfc120deu\.dll",
    r"mfc120enu\.dll",
    r"mfc120esn\.dll",
    r"mfc120fra\.dll",
    r"mfc120ita\.dll",
    r"mfc120jpn\.dll",
    r"mfc120kor\.dll",
    r"mfc120rus\.dll",
    # VC120.OPENMP
    r"vcomp120\.dll",
    # DIA SDK
    r"msdia120\.dll",
    # Cpp REST Windows SDK
    r"casablanca120.winrt\.dll",
    # Mobile Services Cpp Client
    r"zumosdk120.winrt\.dll",
    # Cpp REST SDK
    r"casablanca120\.dll",
    # Universal C Runtime Library (since Visual Studio 2015)
    #
    # NOTE: these should be put under a switch, as they need not to be bundled if deployment target is Windows 10
    # and later, as "UCRT is now a system component in Windows 10 and later, managed by Windows Update".
    # (https://docs.microsoft.com/en-us/cpp/windows/determining-which-dlls-to-redistribute?view=msvc-170)
    # And as discovered in #6326, Windows prefers system-installed version over the bundled one, anyway
    # (see https://docs.microsoft.com/en-us/cpp/windows/universal-crt-deployment?view=msvc-170#local-deployment).
    r"api-ms-win-core.*",
    r"api-ms-win-crt.*",
    r"ucrtbase\.dll",
    # Visual Studio 2015/2017/2019/2022 (VC14) runtime
    # https://docs.microsoft.com/en-us/visualstudio/releases/2022/redistribution
    #
    # VC141.CRT/VC142.CRT/VC143.CRT
    r"concrt140\.dll",
    r"msvcp140\.dll",
    r"msvcp140_1\.dll",
    r"msvcp140_2\.dll",
    r"msvcp140_atomic_wait\.dll",
    r"msvcp140_codecvt_ids\.dll",
    r"vccorlib140\.dll",
    r"vcruntime140\.dll",
    r"vcruntime140_1\.dll",
    # VC141.CXXAMP/VC142.CXXAMP/VC143.CXXAMP
    r"vcamp140\.dll",
    # VC141.OpenMP/VC142.OpenMP/VC143.OpenMP
    r"vcomp140\.dll",
    # DIA SDK
    r"msdia140\.dll",
    # Allow pythonNN.dll, pythoncomNN.dll, pywintypesNN.dll
    r"py(?:thon(?:com(?:loader)?)?|wintypes)\d+\.dll",
}


class _ArgumentNamespace(argparse.Namespace):
    pkgname: str
    src_paths: Optional[list[str]]
    distpath: str
    workpath: str
    config_file: Optional[str]


def get_argument_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser()
    parser.add_argument("--pkgname", type=str, default="")
    parser.add_argument("--src-paths", type=str, nargs="+")
    parser.add_argument("--distpath", type=str, default="")
    parser.add_argument("--workpath", type=str, default="")
    parser.add_argument("config_file", type=str, nargs="?")
    return parser


class PackageSpec(object):

    def __init__(self, args: _ArgumentNamespace) -> None:
        self.pkgname = args.pkgname
        self.src_paths = args.src_paths or []
        self.workpath = os.path.normpath(os.path.abspath(args.workpath))
        self.hidden_imports: list[str] = []
        self.excludes: list[str] = []
        self._parse_config_file(args.config_file)

        if not args.distpath:
            self.distpath = os.path.abspath(os.path.join("dist", self.pkgname))
        else:
            self.distpath = os.path.normpath(os.path.abspath(args.distpath))
        self._clear_dist_dir()

        self.generated_src_path = os.path.join(self.workpath, "generated")
        self.cmake_build_path = os.path.join(self.workpath, "build")
        self.frozen_module_dir = os.path.join(self.generated_src_path, "frozen_modules")
        self._clear_generated_dir()

        self._frozen_modules: dict[str, str] = {}
        self._ext_modules: dict[str, str] = {}

    def _parse_config_file(self, file_path: Optional[str]) -> None:
        """
        name: str
        src_paths: list[str]
        hidden_imports: list[str]
        excludes: list[str]
        """
        if not file_path:
            return
        if not os.path.isfile(file_path):
            return
        config_module = utils.load_signle_module("PackageSpecConfig", file_path)
        if hasattr(config_module, "name") and isinstance(config_module.name, str):
            self.pkgname = config_module.name
        if hasattr(config_module, "src_paths") and isinstance(config_module.src_paths, list):
            for src_path in config_module.src_paths:
                if isinstance(src_path, str) and src_path not in self.src_paths:
                    self.src_paths.append(src_path)
        if hasattr(config_module, "hidden_imports") and isinstance(config_module.hidden_imports, list):
            for hidden_import in config_module.hidden_imports:
                if isinstance(hidden_import, str) and hidden_import not in self.hidden_imports:
                    self.hidden_imports.append(hidden_import)
        if hasattr(config_module, "excludes") and isinstance(config_module.excludes, list):
            for exclude in config_module.excludes:
                if isinstance(exclude, str) and exclude not in self.excludes:
                    self.excludes.append(exclude)

    def generate_source(self) -> None:
        """
        Generate source files for building package.
        """
        self.make_freeze()
        self.generate_main_c()
        self.generate_cmake_lists_txt()
        self._copy_cpython_dir()

    def build(self) -> int:
        """
        Build source code generated by `generate_source`
        """
        returncode = self._cmake_configure()
        if returncode:
            return returncode
        returncode = self._cmake_build()
        return returncode

    def assemble(self) -> None:
        """
        Assemble the final package to the distpath.
        """
        import_packages = sorted(self._ext_modules.keys())
        if not import_packages:
            return
        pyi_binaries: list[tuple[str, str, str]] = []
        dist_contents = os.listdir(self.distpath)
        assert len(dist_contents) == 1
        pyi_binaries.append((dist_contents[0], os.path.join(self.distpath, dist_contents[0]), "BINARY"))
        for module_name, module_path in self._ext_modules.values():
            level = module_name.count(".") + 1
            file_basename = os.path.basename(module_path)
            if "__init__" in file_basename:
                # __init__.pyd
                level += 1
            pyi_binaries.append(assemble_application.normalize_pyi_toc(module_path, "BINARY", level))

        # Get all dependencies of the binaries using PyInstaller's API
        dependencies = build_main.find_binary_dependencies(pyi_binaries, import_packages, set())
        excludes_regex = re.compile("|".join(_BINARY_EXCLUDES), re.I)
        # Copy all binaries and datas to the output directory
        for dest, src, _ in dependencies:
            if excludes_regex.match(os.path.basename(dest)):
                continue
            dest = os.path.join(self.distpath, dest)
            if os.path.exists(dest):
                continue
            dirname = os.path.dirname(dest)
            if not os.path.isdir(dirname):
                os.makedirs(dirname)
            shutil.copyfile(src, dest)

    def make_freeze(self) -> None:
        """
        Generate all frozen headers for the package spec.
        All result source files will be stored in `frozen_module_dir`.
        """
        self._clear_frozen_module_dir()
        for src_path in self.src_paths:
            for module_name, module_path, is_ext in utils.iterate_module_paths(src_path):
                if is_ext:
                    self._ext_modules[module_name] = module_path
                else:
                    self._frozen_modules[module_name] = module_path
        self._dump_frozen_module_info()
        headers: list[str] = []
        frozen_structs: list[str] = []
        with multiprocessing.Pool(processes=multiprocessing.cpu_count()) as pool:
            for module_name, module_file in self._frozen_modules.items():
                header_name = f"{module_name}.h"
                header_path = os.path.join(self.frozen_module_dir, header_name)
                pool.apply_async(generate_frozen_modules.freeze, args=(module_name, module_file, header_path))
                headers.append(f'#include "{header_name}"')
                varname = generate_frozen_modules.get_module_varname(module_name, "_Py_M__")
                is_package_literal = "1" if generate_frozen_modules.file_is_package(module_file) else "0"
                frozen_struct_literal = f'    {{"{module_name}", {varname}, (int)sizeof({varname}), {is_package_literal}}},'
                frozen_structs.append(frozen_struct_literal)
            pool.close()
            pool.join()
        headers_literal = "\n".join(headers)
        frozen_structs_literal = "\n".join(frozen_structs)
        frozen_modules_header_src = FROZEN_MODULES_HEADER_SRC.format(frozen_headers=headers_literal, module_infos=frozen_structs_literal)
        frozen_modules_header_path = os.path.join(self.frozen_module_dir, "frozen_modules.h")
        log.logger.info("Generating: %s", frozen_modules_header_path)
        with open(frozen_modules_header_path, "w", encoding="utf-8") as fp:
            fp.write(frozen_modules_header_src)

    def generate_main_c(self) -> None:
        main_c_src = MAIN_C_SRC.format(pkgname=self.pkgname)
        main_c_path = os.path.join(self.generated_src_path, "main.c")
        log.logger.info("Generating: %s", main_c_path)
        with open(main_c_path, "w", encoding="utf-8") as fp:
            fp.write(main_c_src)

    def generate_cmake_lists_txt(self) -> None:
        cmake_script_src = CMAKE_SRC.format(pkgname=self.pkgname)
        cmake_script_path = os.path.join(self.generated_src_path, "CMakeLists.txt")
        log.logger.info("Generating: %s", cmake_script_path)
        with open(cmake_script_path, "w", encoding="utf-8") as fp:
            fp.write(cmake_script_src)

    def _copy_cpython_dir(self) -> None:
        """
        Copy cpython directory to the generated directory.
        """
        src_dir = os.path.join(paths.CPP_SRC, "tfloader", "cpython")
        dest_dir = os.path.join(self.generated_src_path, "cpython")
        shutil.copytree(src_dir, dest_dir)

    def _clear_dist_dir(self) -> None:
        """
        Clear dist directory
        """
        if os.path.isdir(self.distpath):
            shutil.rmtree(self.distpath)
        os.makedirs(self.distpath)

    def _clear_generated_dir(self) -> None:
        """
        Clear generated directory
        """
        if os.path.isdir(self.generated_src_path):
            shutil.rmtree(self.generated_src_path)
        os.makedirs(self.generated_src_path)

    def _clear_frozen_module_dir(self) -> None:
        """
        Clear frozen module directory
        """
        if os.path.isdir(self.frozen_module_dir):
            shutil.rmtree(self.frozen_module_dir)
        os.makedirs(self.frozen_module_dir)

    def _dump_frozen_module_info(self) -> None:
        """
        Dump frozen module info to workpath
        """
        info_file = os.path.join(self.workpath, "frozen_module_cache")
        info_file_contents = ["FROZEN_MODULES = {"]
        for module_name in sorted(self._frozen_modules.keys()):
            file_path = self._frozen_modules.get(module_name, "Unknown file")
            info_file_contents.append(f'    "{module_name}": r"{file_path}",')
        info_file_contents.append("}")
        info_file_contents.append("")  # extra empty line to make the file prettier
        with open(info_file, "w", encoding="utf-8") as fp:
            fp.write("\n".join(info_file_contents))

    def _cmake_configure(self) -> int:
        if not paths.CMAKE_EXE:
            log.logger.error("CMake is not installed in your computer.")
            return 1
        python_exe = paths.PYTHON_EXE.replace("\\", "/")
        distpath = self.distpath.replace("\\", "/")
        cmake_args = [
            paths.CMAKE_EXE,
            "-B",
            self.cmake_build_path,
            "-S",
            self.generated_src_path,
            f"-DPYTHON_EXECUTABLE={python_exe}",
            f"-DCMAKE_LIBRARY_OUTPUT_DIRECTORY={distpath}",
        ]
        cmake_cache = os.path.join(self.cmake_build_path, "CMakeCache.txt")
        if os.path.isfile(cmake_cache):
            log.logger.debug("CMakeCache.txt exists, pending to remove it.")
            os.remove(cmake_cache)
        log.logger.info("CMake: Configure")
        returncode = utils.call_subprocess(cmake_args, cwd=os.getcwd())
        return returncode

    def _cmake_build(self) -> int:
        if not paths.CMAKE_EXE:
            log.logger.error("CMake is not installed in your computer.")
            return 1
        cmake_args = [
            paths.CMAKE_EXE,
            "--build",
            self.cmake_build_path,
            "--config",
            "Release",
        ]
        log.logger.info("CMake: Build")
        returncode = utils.call_subprocess(cmake_args, cwd=os.getcwd())
        return returncode


def main() -> int:
    """
    Entry point
    """
    try:
        parser = get_argument_parser()
        namespace = _ArgumentNamespace()
        args = parser.parse_args(sys.argv[1:], namespace)

        spec = PackageSpec(args)
        spec.generate_source()
        retcode = spec.build()
        if retcode:
            return retcode
        spec.assemble()
        return 0
    except KeyboardInterrupt:
        log.logger.info("Keyboard Interrupt.")
        utils.close_all_log_pipe()
        return 1


if __name__ == "__main__":
    sys.exit(main())
