# -*- coding: utf-8 -*-
# author: Tac
# contact: cookiezhx@163.com

import types

__version__ = ...  # type: str

def load_tfpackage(pkg_name: str, pkg_path: str, /) -> bool: ...
def is_tfpackage_frozen(name: str, /) -> bool: ...
def is_tfpackage_frozen_package(name: str, /) -> bool: ...
def get_tfpackage_frozen_object(name: str, /) -> types.CodeType: ...
def find_tfpackage_frozen(name: str, /) -> tuple[bool, str | None] | None: ...
